status = warn
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

logger.app.name = com.gastongg.iot
logger.app.level = info
